### ISSUE TITLE
Tidak berfungsi 

### ISSUE THREAD

**Issue by rayhanoratamaja** [BryanGIG/BypassDANA#1]
Mental ketika buka dana

**Comment by BryanGIG** [comment]
Ada log crashnya?

**Comment by BryanGIG** [comment]
Tak rekomendasikan pake DANA v2.56.1

**Comment by BryanGIG** [comment]
Fixed, try [v2.5.0 release](https://github.com/BryanGIG/BypassDANA/releases/download/2.5.0/BypassDANA-2.5.0.apk)
